# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mzyFEl--QUborU-j00ByytDLrnSUsdry

# **Subject**: Data Analysis & Visualization Tasks – Website Traffic & Conversion Data


- **Dataset** - WebTraffic_Q1_2025.csv

(https://docs.google.com/spreadsheets/d/1ukuFijyn5kqMadhPrrzi-X840gFMpoLZhp3tyWJWR8E/edit?usp=sharing)
"""

import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns

df = pd.read_csv('/content/WebTraffic_Q1_2025 - WebTraffic_Q1_2025.csv.csv')
df.head()

df.info()

"""## 1. Data Preparation:"""

# Parse the 'VisitDate' column into datetime format
df['VisitDate'] = pd.to_datetime(df['VisitDate'])

# Create new columns for Month, Day of Week, and Week Number.
df['Month'] = df['VisitDate'].dt.month_name()
df['Day of Week'] = df['VisitDate'].dt.day_name()
df['Week Number'] = df['VisitDate'].dt.isocalendar().week
# df.head()

# Handle any missing or malformed data entries, particularly in the 'SessionDuration' and 'PageViews' columns.
# df.isnull().sum()
df['SessionDuration'] = df['SessionDuration'].fillna(df['SessionDuration'].mean())
df['PageViews'] = df['PageViews'].fillna(df['PageViews'].median())
df.isnull().sum()

"""## 2. Traffic Trend Analysis:"""

# Plot the daily number of sessions over time for Q1.
daily_sessions = df.groupby('VisitDate').size()
# daily_sessions

plt.figure(figsize=(7,5))
daily_sessions.plot()
plt.title('Daily Number of Sessions')
plt.xlabel('Date')
plt.ylabel('Sessions')
plt.tight_layout()
plt.show()

# Generate a line chart comparing weekly traffic trends across January, February, and March.

weekly_trends = df.groupby(['Week Number','Month']).size().unstack().fillna(0)
# weekly_trends

weekly_trends.plot(figsize=(7,5), marker='o')
plt.title('Weekly Traffic Trends by Month')
plt.xlabel('Week Number')
plt.ylabel('Sessions')
plt.tight_layout()
plt.show()

"""## 3. User Engagement Metrics:"""

# Calculate the average session duration and average page views per session.
avg_session_duration = df['SessionDuration'].mean()
avg_page_views = df['PageViews'].mean()

print(f'Average Session Duration : {avg_session_duration:.2f} seconds. \nAverage PAge Views per Session : {avg_page_views:.2f}')

# Identify the top 5 referral sources bringing the most traffic and visualize this with a horizontal bar chart.
top_refrral_source = df['ReferralSource'].value_counts().head(5)
print(top_refrral_source)

top_refrral_source.plot(kind='barh', figsize=(7,3), color='pink')
plt.title('Top 5 Referrance Source')
plt.xlabel('Sessions')
plt.tight_layout()
plt.show()

"""## 4. Conversion Analysis:"""

# Calculate the overall conversion rate (Total conversions / Total sessions).
conversion_rate = df['Conversions'].mean()*100
print(f'Overall Conversion Rate : {conversion_rate:.2f} %')

# Plot a pie chart showing the distribution of conversion sources (e.g., Direct, Organic, Paid, Referral).
conversion_source = df[df['Conversions']==1]['ReferralSource'].value_counts()
conversion_source.plot(kind='pie', autopct='%0.2f%%', figsize=(5,5), startangle=90)
plt.title('Distribution of Conversion Sources')
plt.tight_layout()
plt.show()

"""## 5. Device & Platform Insights:"""

# Group data by device type (Desktop, Mobile, Tablet) and show average session duration for each.
device_duration = df.groupby('DeviceType')['SessionDuration'].mean()

device_duration.plot(kind='bar', figsize=(5,4))
plt.title('Average Session Duratoion by Devicetype')
plt.tight_layout()
plt.show()

# Plot a grouped bar chart of conversion rate by device type.
device_conversion = df.groupby('DeviceType')['Conversions'].mean()*100
device_conversion.plot(kind='bar', figsize=(5,4))
plt.title('Conversion Rate by Device')
plt.tight_layout()
plt.show()

"""## 6. Bounce Rate Pattern:"""

from matplotlib.lines import lineStyles
# Plot a line graph of average daily bounce rate.
daily_bounce = df.groupby('VisitDate')['BounceRate'].mean()
daily_bounce.plot(kind='line', figsize=(5,4))
plt.title('Average Daily Bounce Rate')
plt.tight_layout()

# Highlight days where the bounce rate exceeded 70%.
plt.axhline(70, linestyle='--', color='orange', label='70% Threshold line')
plt.show()

